### ISSUE TITLE
New compatibility for Carpet-AMS-Addition / 1.20.4 Version

### ISSUE THREAD

**Issue by sternschnaube** [RealMegaMinds/ClickOpener#16] opened 2024-02-13 22:57 UTC
Encountered an unexpected exception
java.lang.NoClassDefFoundError: club/mcams/carpet/screen/largeShulkerBox/largeShulkerBoxScreenHandler
        at megaminds.clickopener.compat.CarpetAMSAdditionCompat.register(CarpetAMSAdditionCompat.java:31) ~[clickopener-3.0.3+1.20.1.jar:?]
        at megaminds.clickopener.api.HandlerRegisterEvent.lambda$static$0(HandlerRegisterEvent.java:15) ~[clickopener-3.0.3+1.20.1.jar:?]
        at megaminds.clickopener.api.HandlerRegistry.onServerLoading(HandlerRegistry.java:20) ~[clickopener-3.0.3+1.20.1.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-df781ed0de5bc62e.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cjp000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:8409) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: club.mcams.carpet.screen.largeShulkerBox.largeShulkerBoxScreenHandler
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 8 more

______________________

More details about it here: https://github.com/Minecraft-AMS/Carpet-AMS-Addition/issues/81

**Comment by Hoid2** [comment] 2024-02-14 01:03
Duplicate of #15

**Closed as not planned by Hoid2** 2024-02-14 01:03 UTC

**Comment by sternschnaube** [comment] 2024-02-14 02:40
Thanks, sorry I did not checked the other issues.

**Comment by Hoid2** [comment] 2024-02-26 16:49
This [version](https://modrinth.com/mod/clickopener/version/4.0.0-alpha+1.20.1) should work for 1.20.1 and 1.20.2. Later versions are still in progress.

**Comment by sternschnaube** [comment] 2024-02-26 17:09
Thanks, if the 1.20.4 version is out I will test it 😊
